### ISSUE TITLE
CKEditor Configuration.

### ISSUE THREAD

**Issue by Franckeddy** [opera-project/OperaMediaBundle#6]
Configuration of CKeditor is not customizable in fields that are not subject to opera_media_bundle.

<img width="794" alt="Screenshot 2019-03-19 at 13 20 55" src="https://user-images.githubusercontent.com/44127500/54605615-f3829480-4a49-11e9-9db4-cfebd992cef2.png">
<img width="679" alt="Screenshot 2019-03-19 at 13 17 25" src="https://user-images.githubusercontent.com/44127500/54605400-77884c80-4a49-11e9-9db8-4c5152a7c141.png">
<img width="824" alt="Screenshot 2019-03-19 at 13 17 33" src="https://user-images.githubusercontent.com/44127500/54605409-79eaa680-4a49-11e9-9eca-839111f1ee79.png">
<img width="1013" alt="Screenshot 2019-03-19 at 13 17 58" src="https://user-images.githubusercontent.com/44127500/54605412-7bb46a00-4a49-11e9-9c97-f98269a1681a.png">

Return:

![Screenshot 2019-03-19 at 13 19 43](https://user-images.githubusercontent.com/44127500/54605659-114ff980-4a4a-11e9-83fb-ae1e46515f33.png)
ExtraPlugin
![Screenshot 2019-03-19 at 13 20 07](https://user-images.githubusercontent.com/44127500/54605666-14e38080-4a4a-11e9-96da-375b894397ab.png)

**Comment by cedriclombardot** [comment]
This issue is not related to media bundle !

**Comment by cedriclombardot** [comment]
Not related to opera
